# Generated by Django 4.0.4 on 2022-09-29 01:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True, max_length=20, null=True)),
                ('bloodbank_name', models.CharField(help_text='اﻻسم', max_length=100, null=True)),
                ('bloodbank_addr', models.CharField(help_text='العنوان', max_length=255, null=True)),
                ('type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='نوع فصيلة الدم', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, default=None, help_text='رقم الهاتف المحمول', max_length=11, null=True)),
                ('city', models.CharField(choices=[('جوجر', 'جوجر'), ('ميت الكرماء', 'ميت الكرماء')], help_text='القرية', max_length=50, null=True)),
                ('count_views', models.IntegerField(blank=True, default=0, null=True)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('likeBloodbank', models.ManyToManyField(blank=True, related_name='likeBloodbank', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(max_length=5000, null=True, verbose_name='التعليق')),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.bloodbank')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
