# Generated by Django 4.0.4 on 2022-09-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='last_donation',
            field=models.DateField(blank=1, null=1),
            preserve_default=1,
        ),
    ]
