# Generated by Django 4.0.4 on 2022-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bloodbank_last_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='ready_to_donation',
            field=models.CharField(blank=1, choices=[('جاهز', 'جاهز'), ('غير جاهز', 'غير جاهز')], default=None, max_length=20, null=1),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='last_donation',
            field=models.DateField(blank=1, default=None, null=1),
        ),
    ]
